export const environment = {
  production: true,
  baseUrl: 'https://auctions.senarly.com/api/',
  register: 'register',
  login: 'login',
  cities: 'cities',
  auctions: 'auctions',
  auction: 'auction',
  comments: 'comments',
  percentage: 'percentage',
  add: 'add',
  fish: 'fish',
  categories: 'categories',
  settings: 'settings',
  profile: 'profile',
  search: 'search',
  check: 'check',
  visitors: 'visitors',
};
